services:
  next-app:
    container_name: hello-k8s-next-app-dev
    image: hello-k8s-next-app-dev
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the compose file
    # environment:
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7.4.1-alpine
    # ports:
    #   - 6379:6379
    volumes:
      - "./redis/data:/data"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 5s
      retries: 15
