services:
  next-app:
    container_name: hello-k8s-next-app
    image: hello-k8s-next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile

    # Set environment variables directly in the compose file
    # environment:
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    restart: always
    ports:
      - 3000:3000
    # depends_on:
    #   redis:
    #     condition: service_healthy
