resources:
  - ../../base
secretGenerator:
  - name: caddy-secret
    envs:
      - caddy/.env
patchesStrategicMerge:
  - backend/deployment.yaml
  - worker/deployment.yaml
  - caddy/deployment.yaml
  - next-app/deployment.yaml
