apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    spec:
      containers:
        - name: worker
          command:
            - npm
            - run
            - dev:worker
          volumeMounts:
            - name: worker-src
              mountPath: /app/src
              readOnly: false
      volumes:
        - name: worker-src
          hostPath:
            path: /workspace/hello-k8s/backend/src
            type: Directory
