apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z redis 6379; do
                echo "Waiting for redis...";
                sleep 2;
              done;
              until nc -z minio 9000; do
                echo "Waiting for minio...";
                sleep 2;
              done;
      containers:
        - name: worker
          image: hello-k8s-backend
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: minio-secret
