apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z backend 4000; do
                echo "Waiting for backend...";
                sleep 2;
              done;
      containers:
        - name: next-app
          image: hello-k8s-next-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
