apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  labels:
    app: caddy
data:
  Caddyfile: |
    {$DOMAIN_NAME:localhost} {
        tls {$TLS_EMAIL:internal}

        handle /api/* {
            reverse_proxy backend:4000
        }

        handle /admin/* {
            reverse_proxy backend:4000
        }

        handle {
            reverse_proxy next-app:3000
        }
    }
