apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2.10.0-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
      volumes:
        - name: caddyfile
          configMap:
            name: caddy-config
            items:
              - key: Caddyfile
                path: Caddyfile
        - name: data
          emptyDir: {}
        - name: config
          emptyDir: {}
