apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    app: caddy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
